name: Docker Build 3-tier image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: listing content
        working-directory: scripts  
        run: 
         ls -al

      - name: Install dependencies
        run: |
          chmod +x install-update.sh
          ./install-update.sh

  build_database:
    runs-on: self-hosted
    needs: [install_dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build database Docker image
        id: build_database_image
        working-directory: t1-database
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-database:stable -t ${{ secrets.DOCKER_USERNAME }}/todo-database:$(git rev-parse HEAD) .

  build_backend:
    runs-on: self-hosted
    needs: [install_dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        id: build_backend_image
        working-directory: t2-backend
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:stable -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:$(git rev-parse HEAD) .

  build_frontend:
    runs-on: self-hosted
    needs: [install_dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend Docker image
        id: build_frontend_image
        working-directory: t3-frontend
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:stable -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:$(git rev-parse HEAD) .
        
  list_images:
    runs-on: self-hosted
    needs: [build_database, build_backend, build_frontend]
    steps:
      - name: List Docker images
        run: |
          sudo docker images

  deploy:
    needs: [list_images]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          sudo docker-compose -f ../docker-compose.yml up -d

  push_images:
    runs-on: self-hosted
    needs: [deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Push Database Docker images
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:stable
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-database:$(git rev-parse HEAD)
      
      - name: Push Backend Docker images
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:stable
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:$(git rev-parse HEAD)
      
      - name: Push Frontend Docker images
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:stable
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:$(git rev-parse HEAD)
      
      - name: Logout from Docker Hub
        run: docker logout
